version: '3.9'

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    extra_hosts:
      - "databaseRent:172.55.0.4"
      - "databaseUser:172.55.0.3"
      - "appserver:172.25.0.2"
    volumes:
      - ./create_users.sh:/docker-entrypoint-initdb.d/create_users.sh
    networks:
      tks:
        ipv4_address: 172.55.0.5

  payara:
    image: payara/server-full:5.2022.4-jdk17
    ports:
      - "8080:8080"
      - "4848:4848"
      - "9009:9009"
    extra_hosts:
      - "databaseRent:172.55.0.4"
      - "databaseUser:172.55.0.3"
    networks:
      tks:
        ipv4_address: 172.55.0.2
    environment:
      - JVM_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9009
#    volumes:
#      - ../RestAdapter/target/RestAdapter-1.0-SNAPSHOT.war:/opt/payara/deployments/RestAdapter-1.0-SNAPSHOT.war

  db-rent:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - "5433:5432"
    networks:
      tks:
        ipv4_address: 172.55.0.3
  db-user:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - "5432:5432"
    networks:
      tks:
        ipv4_address: 172.55.0.4

networks:
  tks:
    driver: bridge
    ipam:
      config:
        - subnet: 172.55.0.0/24
